version: '3'

services:
  webshop-react-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    container_name: hangtal_new
    networks:
      - web
      - internal
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.webshop-frontend.rule=Host(`${WORDPRESS_SITE_URL_HOST}`)"
      - "traefik.http.routers.webshop-frontend.entrypoints=websecure"
      - "traefik.http.routers.webshop-frontend.tls.certresolver=cloudflare"
      - "traefik.http.services.webshop-frontend.loadbalancer.server.port=80"
      - "traefik.docker.network=web"
      - "traefik.http.routers.webshop-redirect.rule=Host(`www.${WORDPRESS_SITE_URL_HOST}`)"
      - "traefik.http.routers.webshop-redirect.entrypoints=websecure"
      - "traefik.http.routers.webshop-redirect.middlewares=redirect-nonwww"
      - "traefik.http.middlewares.redirect-nonwww.redirectregex.regex=^https://www\\.(.+)"
      - "traefik.http.middlewares.redirect-nonwww.redirectregex.replacement=https://$$1"

networks:
  web:
    external: true
  internal:
    internal: true
